site_name: Отчёт по практической работе
theme:
  name: material
nav:
  - Главная: index.md
  - Практическая работа 2.1: practice1.md
  - Практическая работа 2.2: practice2.md
  - Практическая работа 2.3: practice3.md